#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          energyconsole
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Energy Monitor API
# Description:       Console and API for energy monitoring
### END INIT INFO

# Author: DeckerEgo <john@deckerego.net>

DESC="EnergyMonitor API"
NAME="energyconsole"
DAEMON_PATH="/opt/$NAME"
DAEMON="$DAEMON_PATH/bin/$NAME"
PIDFILE="$DAEMON_PATH/RUNNING_PID"

do_start_cmd() {
        start-stop-daemon --start --quiet --pidfile ${PIDFILE} \
            $START_ARGS \
            --startas $DAEMON --name $NAME --exec $DAEMON --test > /dev/null \
            || return 1
        start-stop-daemon --start --background --pidfile ${PIDFILE} \
            $START_ARGS \
            --startas $DAEMON --name $NAME --exec $DAEMON -- $DAEMON_ARGS \
            || return 2
}
